#!/usr/bin/env python3
"""Pack template/ and components/ into src/embed_gen.src so the binary carries
its own registry (same move as `machin guide`: version-exact, offline,
self-describing). Component descriptions come from each file's first-line
comment ("// <name>.src — description")."""
import json, pathlib, re

ROOT = pathlib.Path(__file__).parent.parent

lines = ["// embed_gen.src — GENERATED by tools/gen_embed.py. Do not hand-edit."]

lines += ["func embed_template() (m) {", "    m = make(map[string]string)"]
tpl = ROOT / "template"
for p in sorted(tpl.rglob("*")):
    if p.is_file():
        rel = str(p.relative_to(tpl))
        lines.append(f"    m[{json.dumps(rel)}] = {json.dumps(p.read_text())}")
lines.append("}")

comps, descs = {}, {}
for p in sorted((ROOT / "components").glob("*.src")):
    name = p.stem
    comps[name] = p.read_text()
    m = re.match(r"//\s*\S+\s+—\s+(.+)", comps[name].splitlines()[0])
    descs[name] = m.group(1).strip() if m else ""

lines += ["func embed_components() (m) {", "    m = make(map[string]string)"]
for n, c in comps.items():
    lines.append(f"    m[{json.dumps(n)}] = {json.dumps(c)}")
lines.append("}")
lines += ["func embed_component_descs() (m) {", "    m = make(map[string]string)"]
for n, d in descs.items():
    lines.append(f"    m[{json.dumps(n)}] = {json.dumps(d)}")
lines.append("}")

(ROOT / "src/embed_gen.src").write_text("\n".join(lines) + "\n")
print(f"{sum(1 for p in tpl.rglob('*') if p.is_file())} template files, {len(comps)} components -> src/embed_gen.src")
